const MODALS = {
  MENU_ID: 1,
  CART_ID: 2,
  FILTER_SORT_ID: 3,
  FILTER_BRAND_ID: 4,
  ALL_FILTERS: 5,
  MEGA_NAV_MEN_ID: 6,
  MEGA_NAV_WOMEN_ID: 7,
  MEGA_NAV_WATCHES_ID: 8,
  MEGA_NAV_SCHOES_ID: 9
}

export default MODALS
